import { create } from "zustand";

export type Language = "zh" | "en";

export type TranslationKey = keyof typeof translations.zh;

type SettingsState = {
  language: Language;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
};

const languageStorageKey = "account-service.language";

function readInitialLanguage(): Language {
  if (typeof window === "undefined") {
    return "zh";
  }
  return window.localStorage.getItem(languageStorageKey) === "en" ? "en" : "zh";
}

function persistLanguage(language: Language) {
  if (typeof window !== "undefined") {
    window.localStorage.setItem(languageStorageKey, language);
  }
}

export const translations = {
  zh: {
    "app.brand": "账号服务后台",
    "app.meta": "运营控制台",
    "common.cancel": "取消",
    "common.close": "关闭",
    "common.copy": "复制",
    "common.createdAt": "创建时间",
    "common.create": "创建",
    "common.delete": "删除",
    "common.disabled": "禁用",
    "common.edit": "编辑",
    "common.filter": "筛选",
    "common.reveal": "查看",
    "common.save": "保存",
    "common.serviceOnline": "服务在线",
    "common.settings": "设置",
    "common.signOut": "退出登录",
    "common.status": "状态",
    "common.updatedAt": "更新时间",
    "common.usable": "可用",
    "common.view": "查看",
    "language.current": "中文",
    "login.description": "登录后管理账号、租约、API Key 和审计日志。",
    "login.errorTitle": "登录失败",
    "login.form": "管理员登录",
    "login.password": "密码",
    "login.submit": "登录",
    "login.submitting": "登录中",
    "login.username": "用户名",
    "nav.accounts": "账号管理",
    "nav.apiKeys": "Key 管理",
    "nav.auditLogs": "审计日志",
    "nav.leases": "租约管理",
    "nav.label": "后台导航",
    "nav.modelConfig": "模型管理",
    "nav.overview": "概览",
    "overview.auditLabel": "审计链路",
    "overview.auditValue": "已追踪",
    "overview.description": "集中查看账号容量、租约分配、调用凭证和审计活动。",
    "overview.leaseLabel": "租约流程",
    "overview.leaseValue": "受控",
    "overview.securityLabel": "安全策略",
    "overview.securityValue": "JWT 认证",
    "overview.title": "运营概览",
    "overview.workspaceLabel": "核心工作区",
    "overview.workspaceValue": "账号管理",
    "accounts.accessToken": "Access Token",
    "accounts.account": "账号",
    "accounts.accountType": "账号类型",
    "accounts.activeAccounts": "活跃账号",
    "accounts.add": "添加账号",
    "accounts.applyFilters": "筛选",
    "accounts.createdAt": "创建时间",
    "accounts.createDescription": "新增一个用于分配和额度跟踪的账号记录。",
    "accounts.deleteConfirm": "确认删除",
    "accounts.deleteDescriptionPrefix": "将删除",
    "accounts.deleteDescriptionSuffix": "，此操作不可撤销。",
    "accounts.deleteTitle": "删除账号",
    "accounts.description": "管理账号库存、额度、凭证和运行状态。",
    "accounts.detailsTitle": "账号详情",
    "accounts.editDescription": "更新凭证、状态、额度或路由元数据。",
    "accounts.editTitle": "编辑账号",
    "accounts.empty": "暂无账号",
    "accounts.errorStates": "异常状态",
    "accounts.errorTitle": "账号暂不可用",
    "accounts.inventory": "账号列表",
    "accounts.filterTitle": "筛选条件",
    "accounts.id": "ID",
    "accounts.kiroAuthMethod": "Kiro 认证方式",
    "accounts.kiroExpiresAt": "Kiro 过期时间",
    "accounts.kiroLogin": "账号登录",
    "accounts.kiroLoginCanceling": "正在取消 Kiro 登录...",
    "accounts.kiroLoginConfirm": "确认登录",
    "accounts.kiroLoginConfirmDescription": "确认要开始 Kiro 登录：",
    "accounts.kiroLoginConfirmTitle": "确认账号登录",
    "accounts.kiroLoginDescription": "正在启动 Kiro CLI 登录：",
    "accounts.kiroLoginRunning": "请在收到的 Kiro 登录链接中完成授权。",
    "accounts.kiroLoginTargetUrl": "Kiro 登录链接",
    "accounts.kiroLoginTargetUrlWaiting": "正在等待 Kiro CLI 输出登录链接...",
    "accounts.kiroLoginTimeout": "2 分钟后仍未完成会自动取消。",
    "accounts.kiroProfileArn": "Kiro Profile ARN",
    "accounts.kiroProvider": "Kiro Provider",
    "accounts.loading": "账号加载中",
    "accounts.loginUrl": "登录地址",
    "accounts.maxLeases": "最大租约数",
    "accounts.minQuota": "最低额度",
    "accounts.noLoginUrl": "无登录地址",
    "accounts.notes": "备注",
    "accounts.password": "密码",
    "accounts.providerAccessToken": "Access Token",
    "accounts.providerRefreshToken": "Refresh Token",
    "accounts.quota": "额度",
    "accounts.quotaRemaining": "剩余额度",
    "accounts.quotaTotal": "总额度",
    "accounts.quotaUsed": "已用额度",
    "accounts.refreshToken": "Refresh Token",
    "accounts.region": "区域",
    "accounts.regions": "区域数",
    "accounts.status": "状态",
    "accounts.tags": "标签",
    "accounts.tagsPlaceholder": "openai, paid",
    "accounts.title": "账号管理",
    "accounts.type": "类型",
    "accounts.typeAll": "全部类型",
    "accounts.updatedAt": "更新时间",
    "accounts.username": "用户名",
    "accounts.statusAll": "全部状态",
    "apiKeys.cardDescription": "明文 Key 仅在创建成功后展示一次。",
    "apiKeys.cardTitle": "API Key 列表",
    "apiKeys.create": "创建 API Key",
    "apiKeys.deleteConfirm": "确认删除",
    "apiKeys.deleteDescription": "删除后外部服务将无法再使用该调用凭证：",
    "apiKeys.deleteTitle": "删除 API Key",
    "apiKeys.description": "维护服务间访问调用凭证。",
    "apiKeys.editTitle": "编辑 API Key",
    "apiKeys.empty": "暂无 API Key",
    "apiKeys.error": "API Key 操作失败",
    "apiKeys.fieldDescription": "描述",
    "apiKeys.fieldName": "名称",
    "apiKeys.save": "保存 API Key",
    "apiKeys.secretLabel": "API Key",
    "apiKeys.title": "Key 管理",
    "audit.actor": "操作者",
    "audit.action": "操作",
    "audit.cardDescription": "敏感元数据由 API 返回前完成脱敏。",
    "audit.cardTitle": "活动流",
    "audit.description": "通过请求链路追踪管理端和调用方活动。",
    "audit.empty": "暂无审计日志",
    "audit.metadata": "元数据",
    "audit.requestId": "请求 ID",
    "audit.title": "审计日志",
    "leases.accountId": "账号 ID",
    "leases.activity": "租约活动",
    "leases.cardDescription": "按 active、released 或 expired 状态过滤。",
    "leases.description": "查看当前和历史账号租约分配。",
    "leases.empty": "暂无租约",
    "leases.filter": "筛选租约",
    "leases.filters": "租约筛选",
    "leases.leaseId": "租约 ID",
    "leases.status": "租约状态",
    "leases.title": "租约管理",
    "modelConfig.actions": "操作",
    "modelConfig.create": "创建配置",
    "modelConfig.createTitle": "新增模型配置",
    "modelConfig.deleteConfirm": "确认删除",
    "modelConfig.deleteDescription": "删除后外部服务将不再读取该模型配置：",
    "modelConfig.deleteTitle": "删除模型配置",
    "modelConfig.description": "维护对外服务动态读取的模型列表、隐藏模型和别名规则。",
    "modelConfig.editTitle": "编辑模型配置",
    "modelConfig.empty": "暂无模型配置",
    "modelConfig.error": "模型配置操作失败",
    "modelConfig.filterTitle": "筛选条件",
    "modelConfig.formDescription": "fallback 和 hidden_from_list 使用键字段；hidden_model 和 model_alias 需要填写值字段。",
    "modelConfig.key": "键",
    "modelConfig.kind": "类型",
    "modelConfig.kindAll": "全部类型",
    "modelConfig.listTitle": "模型配置项",
    "modelConfig.order": "排序",
    "modelConfig.save": "保存配置",
    "modelConfig.statusAll": "全部状态",
    "modelConfig.title": "模型管理",
    "modelConfig.value": "值",
    "secret.dismiss": "关闭",
  },
  en: {
    "app.brand": "Account Admin",
    "app.meta": "Operations console",
    "common.cancel": "Cancel",
    "common.close": "Close",
    "common.copy": "Copy",
    "common.createdAt": "Created at",
    "common.create": "Create",
    "common.delete": "Delete",
    "common.disabled": "Disabled",
    "common.edit": "Edit",
    "common.filter": "Filter",
    "common.reveal": "Reveal",
    "common.save": "Save",
    "common.serviceOnline": "Service online",
    "common.settings": "Settings",
    "common.signOut": "Sign out",
    "common.status": "Status",
    "common.updatedAt": "Updated at",
    "common.usable": "Available",
    "common.view": "View",
    "language.current": "English",
    "login.description": "Sign in to manage accounts, leases, API keys, and audit activity.",
    "login.errorTitle": "Sign in failed",
    "login.form": "Admin login",
    "login.password": "Password",
    "login.submit": "Sign in",
    "login.submitting": "Signing in",
    "login.username": "Username",
    "nav.accounts": "Accounts",
    "nav.apiKeys": "API Keys",
    "nav.auditLogs": "Audit Logs",
    "nav.leases": "Leases",
    "nav.label": "Admin sections",
    "nav.modelConfig": "Models",
    "nav.overview": "Overview",
    "overview.auditLabel": "Audit trail",
    "overview.auditValue": "Tracked",
    "overview.description": "Monitor account capacity, leases, callers, and audit activity from one console.",
    "overview.leaseLabel": "Lease flow",
    "overview.leaseValue": "Managed",
    "overview.securityLabel": "Security posture",
    "overview.securityValue": "JWT auth",
    "overview.title": "Operations overview",
    "overview.workspaceLabel": "Primary workspace",
    "overview.workspaceValue": "Accounts",
    "accounts.accessToken": "Access Token",
    "accounts.account": "Account",
    "accounts.accountType": "Account type",
    "accounts.activeAccounts": "Active accounts",
    "accounts.add": "New account",
    "accounts.applyFilters": "Apply filters",
    "accounts.createdAt": "Created at",
    "accounts.createDescription": "Create an account record for allocation and quota tracking.",
    "accounts.deleteConfirm": "Delete account",
    "accounts.deleteDescriptionPrefix": "Delete",
    "accounts.deleteDescriptionSuffix": ". This action cannot be undone.",
    "accounts.deleteTitle": "Delete account",
    "accounts.description": "Manage account inventory, quota, credentials, and operational state.",
    "accounts.detailsTitle": "Account details",
    "accounts.editDescription": "Update credentials, status, quota, or routing metadata.",
    "accounts.editTitle": "Edit account",
    "accounts.empty": "No accounts",
    "accounts.errorStates": "Error states",
    "accounts.errorTitle": "Accounts unavailable",
    "accounts.inventory": "Account inventory",
    "accounts.filterTitle": "Filters",
    "accounts.id": "ID",
    "accounts.kiroAuthMethod": "Kiro auth method",
    "accounts.kiroExpiresAt": "Kiro expires at",
    "accounts.kiroLogin": "Account login",
    "accounts.kiroLoginCanceling": "Canceling Kiro login...",
    "accounts.kiroLoginConfirm": "Confirm login",
    "accounts.kiroLoginConfirmDescription": "Confirm starting Kiro login for",
    "accounts.kiroLoginConfirmTitle": "Confirm account login",
    "accounts.kiroLoginDescription": "Starting Kiro CLI login for",
    "accounts.kiroLoginRunning": "Complete authorization from the Kiro login link.",
    "accounts.kiroLoginTargetUrl": "Kiro login link",
    "accounts.kiroLoginTargetUrlWaiting": "Waiting for Kiro CLI to output the login link...",
    "accounts.kiroLoginTimeout": "The login will be canceled automatically after 2 minutes.",
    "accounts.kiroProfileArn": "Kiro Profile ARN",
    "accounts.kiroProvider": "Kiro Provider",
    "accounts.loading": "Loading accounts",
    "accounts.loginUrl": "Login URL",
    "accounts.maxLeases": "Max leases",
    "accounts.minQuota": "Min quota",
    "accounts.noLoginUrl": "No login URL",
    "accounts.notes": "Notes",
    "accounts.password": "Password",
    "accounts.providerAccessToken": "Provider access token",
    "accounts.providerRefreshToken": "Provider refresh token",
    "accounts.quota": "Quota",
    "accounts.quotaRemaining": "Quota remaining",
    "accounts.quotaTotal": "Quota total",
    "accounts.quotaUsed": "Quota used",
    "accounts.refreshToken": "Refresh Token",
    "accounts.region": "Region",
    "accounts.regions": "Regions",
    "accounts.status": "Status",
    "accounts.tags": "Tags",
    "accounts.tagsPlaceholder": "openai, paid",
    "accounts.title": "Accounts",
    "accounts.type": "Type",
    "accounts.typeAll": "All types",
    "accounts.updatedAt": "Updated at",
    "accounts.username": "Username",
    "accounts.statusAll": "All statuses",
    "apiKeys.cardDescription": "The plaintext key is shown once after creation.",
    "apiKeys.cardTitle": "API key list",
    "apiKeys.create": "Create API key",
    "apiKeys.deleteConfirm": "Confirm delete",
    "apiKeys.deleteDescription": "External services will stop authenticating with this credential after deletion:",
    "apiKeys.deleteTitle": "Delete API key",
    "apiKeys.description": "Maintain service-to-service caller credentials.",
    "apiKeys.editTitle": "Edit API key",
    "apiKeys.empty": "No API keys",
    "apiKeys.error": "API key operation failed",
    "apiKeys.fieldDescription": "Description",
    "apiKeys.fieldName": "Name",
    "apiKeys.save": "Save API key",
    "apiKeys.secretLabel": "API key",
    "apiKeys.title": "API Keys",
    "audit.actor": "Actor",
    "audit.action": "Action",
    "audit.cardDescription": "Sensitive metadata values are expected to be redacted by the API.",
    "audit.cardTitle": "Activity stream",
    "audit.description": "Review administrative and caller activity with request correlation.",
    "audit.empty": "No audit logs",
    "audit.metadata": "Metadata",
    "audit.requestId": "Request ID",
    "audit.title": "Audit logs",
    "leases.accountId": "Account ID",
    "leases.activity": "Lease activity",
    "leases.cardDescription": "Filter by active, released, or expired status.",
    "leases.description": "Inspect active and historical account lease assignments.",
    "leases.empty": "No leases",
    "leases.filter": "Filter leases",
    "leases.filters": "Lease filters",
    "leases.leaseId": "Lease ID",
    "leases.status": "Lease status",
    "leases.title": "Leases",
    "modelConfig.actions": "Actions",
    "modelConfig.create": "Create config",
    "modelConfig.createTitle": "New model config",
    "modelConfig.deleteConfirm": "Confirm delete",
    "modelConfig.deleteDescription": "External services will stop reading this model config after deletion:",
    "modelConfig.deleteTitle": "Delete model config",
    "modelConfig.description": "Maintain model lists, hidden models, and alias rules consumed by external services.",
    "modelConfig.editTitle": "Edit model config",
    "modelConfig.empty": "No model config items",
    "modelConfig.error": "Model config operation failed",
    "modelConfig.filterTitle": "Filters",
    "modelConfig.formDescription": "Fallback and hidden-from-list items use the key field; hidden models and aliases also require value.",
    "modelConfig.key": "Key",
    "modelConfig.kind": "Type",
    "modelConfig.kindAll": "All types",
    "modelConfig.listTitle": "Model config items",
    "modelConfig.order": "Order",
    "modelConfig.save": "Save config",
    "modelConfig.statusAll": "All statuses",
    "modelConfig.title": "Models",
    "modelConfig.value": "Value",
    "secret.dismiss": "Dismiss",
  },
} as const;

export const useSettingsStore = create<SettingsState>((set, get) => ({
  language: readInitialLanguage(),
  setLanguage(language) {
    persistLanguage(language);
    set({ language });
  },
  toggleLanguage() {
    get().setLanguage(get().language === "zh" ? "en" : "zh");
  },
  t(key) {
    return translations[get().language][key];
  },
}));

export function useI18n() {
  const language = useSettingsStore((state) => state.language);
  const setLanguage = useSettingsStore((state) => state.setLanguage);
  const toggleLanguage = useSettingsStore((state) => state.toggleLanguage);

  return {
    language,
    setLanguage,
    toggleLanguage,
    t: (key: TranslationKey) => translations[language][key],
  };
}
